#!/usr/bin/env python3
"""
Manual SavedModel → TF.js converter sin dependencias problemáticas.
Usa la API programática de TensorFlowJS evitando tensorflow_decision_forests.
"""

import argparse
import json
import logging
import shutil
import sys
from pathlib import Path

# Intenta import sin tensorflow_decision_forests
try:
    # Desactivar el import automático de TF-DF
    sys.modules['tensorflow_decision_forests'] = None
    import tensorflow as tf
    from tensorflowjs.converters import tf_saved_model_conversion_v2
except ImportError as e:
    logging.error(f"Error importando TensorFlowJS: {e}")
    logging.error("Instalando dependencias necesarias...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "tensorflowjs==4.4.0"])
    import tensorflow as tf
    from tensorflowjs.converters import tf_saved_model_conversion_v2

logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)


def convert_saved_model_to_tfjs(
    saved_model_path: str,
    output_path: str,
    quantization: str = "float16"
):
    """
    Convierte SavedModel a TF.js usando la API programática.

    Args:
        saved_model_path: Ruta al SavedModel
        output_path: Directorio de salida para TF.js
        quantization: Tipo de cuantización ('float16', 'uint8', o 'none')
    """

    saved_model_path = Path(saved_model_path)
    output_path = Path(output_path)

    if not saved_model_path.exists():
        raise FileNotFoundError(f"SavedModel no encontrado: {saved_model_path}")

    # Limpiar output si existe
    if output_path.exists():
        logger.info(f"Limpiando directorio existente: {output_path}")
        shutil.rmtree(output_path)

    output_path.mkdir(parents=True, exist_ok=True)

    logger.info(f"Convirtiendo {saved_model_path} → {output_path}")
    logger.info(f"Cuantización: {quantization}")

    # Configurar parámetros de cuantización
    quantization_dtype = None
    if quantization == "float16":
        quantization_dtype = tf.float16
    elif quantization == "uint8":
        quantization_dtype = tf.uint8

    try:
        # Cargar SavedModel
        logger.info("Cargando SavedModel...")
        model = tf.saved_model.load(str(saved_model_path))

        # Convertir a TF.js
        logger.info("Convirtiendo a TF.js...")

        # Opción 1: Usar convert_tf_saved_model directamente
        from tensorflowjs.converters import convert_tf_saved_model

        convert_tf_saved_model(
            str(saved_model_path),
            str(output_path),
            signature_def='serving_default',
            saved_model_tags='serve',
            quantization_dtype_map={
                '*': quantization_dtype
            } if quantization_dtype else None,
            skip_op_check=True,
            strip_debug_ops=True
        )

        logger.info(f"✓ Conversión exitosa")
        logger.info(f"Archivos generados en: {output_path}")

        # Listar archivos generados
        files = list(output_path.glob('*'))
        logger.info(f"\nArchivos generados ({len(files)}):")
        for f in sorted(files):
            size_kb = f.stat().st_size / 1024
            logger.info(f"  {f.name:40s} {size_kb:>10.2f} KB")

        # Calcular tamaño total
        total_size = sum(f.stat().st_size for f in files if f.is_file())
        total_mb = total_size / (1024 * 1024)
        logger.info(f"\nTamaño total: {total_mb:.2f} MB")

        # Verificar model.json
        model_json = output_path / 'model.json'
        if model_json.exists():
            with open(model_json, 'r') as f:
                metadata = json.load(f)
            logger.info(f"\n✓ model.json generado")
            logger.info(f"  Format: {metadata.get('format', 'unknown')}")
            logger.info(f"  Generated by: {metadata.get('generatedBy', 'unknown')}")
        else:
            logger.warning("⚠ model.json NO encontrado")

        return True

    except Exception as e:
        logger.error(f"Error durante la conversión: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    parser = argparse.ArgumentParser(description='Manual SavedModel → TF.js converter')
    parser.add_argument('--saved-model', required=True, help='Ruta al SavedModel')
    parser.add_argument('--output', required=True, help='Directorio de salida TF.js')
    parser.add_argument('--quantization', choices=['float16', 'uint8', 'none'], default='float16')

    args = parser.parse_args()

    success = convert_saved_model_to_tfjs(
        args.saved_model,
        args.output,
        args.quantization
    )

    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
